import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import { MainNav } from "@/components/MainNav";

export const metadata: Metadata = {
  title: "Yosef Blandin",
  description: "Generated by create next app",
  keywords: [
    "Next.js",
    "React",
    "Tailwind CSS",
    "Frontend Developer",
    "Yosef Blandin",
  ],
  authors: [
    {
      name: "Yosef Blandin",
    },
  ],
  icons: {
    icon: { url: "/favicon.svg", type: "image/svg" },
    shortcut: { url: "/favicon.svg", type: "image/svg" },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <header className="fixed z-40 bg-zinc-900 rounded-md bg-clip-padding backdrop-filter backdrop-blur-md bg-opacity-10 w-full">
          <section className="relative flex justify-between lg:justify-start lg:gap-8 xl:gap-16 lg:max-w-lg xl:max-w-xl lg:mx-auto items-center p-3 h-12">
            <p className="font-bold text-zinc-100">Yosef Blandin</p>
            <MainNav />
          </section>
        </header>
        <div className="h-12 bg-zinc-600"></div>
        <section>{children}</section>
      </body>
    </html>
  );
}
