import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import { MainNav } from "@/components/MainNav";

export const metadata: Metadata = {
  title: "Yosef Blandin",
  description: "Generated by create next app",
  keywords: [
    "Next.js",
    "React",
    "Tailwind CSS",
    "Frontend Developer",
    "Yosef Blandin",
  ],
  authors: [
    {
      name: "Yosef Blandin",
    },
  ],
  icons: {
    icon: { url: "/favicon.svg", type: "image/svg" },
    shortcut: { url: "/favicon.svg", type: "image/svg" },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <header className="flex justify-between items-center p-3 z-40 bg-zinc-600 h-12 w-100">
          <p className="font-bold text-zinc-200">Yosef Blandin</p>
          <MainNav />
        </header>
        {children}
      </body>
    </html>
  );
}
